let productos = [
    {
        producto :"Membrana no crack",
        id: 1,
        img : "../assets/img/nocrack.jpg",
        precio: 11000,
        pesoMin: "",
        pesoMax:"40kg",
        descripcion:"Membrana asfáltica con revestimiento de aluminio No Crack y No Crack color de gran resistencia y mayor durabilidad.",
        caracteristicas: "Es una innovación tecnológica desarrollada por MEGAFLEX, generada a partir de aluminio compuesto, que plantea una mejora sustancial en los sistemas que incluyen membranas asfálticas aluminadas, aumentando la seguridad para los usuarios en comparación con las membranas asfálticas hasta ahora conocidas.",
        marca:"",
        categoria:"A",
        oferta: false,
    },
    {
        producto :"Membrana geotrans",
        id: 2,
        img : "../assets/img/geotrans.jpeg",
        precio: 11500,
        pesoMin: "36kg",
        pesoMax:"40kg",
        descripcion:"Membrana asfáltica transitable para impermeabilización de balcones, terrazas, cubiertas transitables y de uso bajo carpeta. En presentaciones de 36kg y 40kg",
        caracteristicas: "",
        marca:"",
        categoria:"A",
        oferta: false,
    },
    {
        producto :"Pintura asfaltica",
        id: 3,
        img : "../assets/img/pinturaAsfaltica.webp",
        precio: 12500,
        pesoMin: "",
        pesoMax:"18kg",
        descripcion:"Imprimante de secado rápido, para utilizar sobre hormigón, superficies cementicias, madera, fibrocemento, superficies metálicas, entre otras.",
        caracteristicas: "Gran adherencia, Secado ultrarrápido ,Ideal para tratamiento anticorrosivo",
        marca:"",
        categoria:"A",
        oferta: false,
    },
    {
        producto :"Pintura Aluminizada",
        id: 4,
        img : "../assets/img/pinturaAluminizada.jpg",
        precio: 10200,
        pesoMin: "",
        pesoMax:"4kg",
        descripcion:"Para el tratamiento y protección del asfalto en solapes de membranas asfálticas con aluminio y/o para pintar y proteger impermeabilizaciones asfálticas y membranas deterioradas.",
        caracteristicas: "Gran adherencia, Secado ultrarrápido ,Ideal para tratamiento anticorrosivo",
        marca:"",
        categoria:"A",
        oferta: false,
    },
    {
        producto :"Membrana Liquida",
        id: 5,
        img : "../assets/img/membranaLiquida.jpg",
        precio: 12800,
        pesoMin: "",
        pesoMax:"20kg",
        descripcion:"Para la impermeabilización y el mantenimiento de cubiertas transitables, de gran resistencia, excelente terminación y esta lista para usar. También recomendada para terminación de membranas geotextil",
        caracteristicas: "",
        marca:"",
        categoria:"A",
        oferta: false,
    },
    {
        producto :"Sikaflex 1A plus",
        id: 6,
        img : "../assets/img/SikaFlex-1A-Plus.webp",
        precio: 5000,
        pesoMin: "300ml",
        pesoMax:"600ml",
        descripcion:"Sikaflex®-1A PLUS es un sellador a base de poliuretano, de un componente, impermeable y de alto rendimiento que cura con la humedad ambiente y  bajo módulo elástico.",
        caracteristicas: "",
        marca:"",
        categoria:"A",
        oferta: false,
    },
    {
        producto :"Sikalatex",
        id: 7,
        img : "../assets/img/sikalatex.jpg",
        precio: 10600,
        pesoMin: "",
        pesoMax:"5L",
        descripcion:"Adhesivo y reforzador para mezclas cementicias.",
        caracteristicas: "SikaLátex® es una emulsión a base de resinas sintéticas, que agregada al agua de empastado de lechadas de cemento, les aporta alta capacidad de adherencia entre diferentes etapas de construcción. Además, incorporado al agua de empastado de morteros, les mejorará la calidad logrando cohesión entre las partículas, aumentando su adherencia, mejorando su flexibilidad y disminuyendo la capacidad de absorber agua.",
        marca:"",
        categoria:"A",
        oferta: false,
    },
    {
        producto :"Sikamonotop 107",
        id: 8,
        img : "../assets/img/SikaMonotop107.jpg",
        precio: 8800,
        pesoMin: "",
        pesoMax:"25kg",
        descripcion:"IMPERMEABILIZANTE CEMENTICIO DE ALTA PERFORMANCE",
        caracteristicas: "Sika MonoTop®-107 Seal es un mortero cementício modificado con polímeros, impermeabilizante y monocomponente. Tolera presión de agua positiva y negativa.",
        marca:"",
        categoria:"A",
        oferta: false,
    },
    {
        producto :"Sellador Sikacryl",
        id: 9,
        img : "../assets/img/SikacrylProfesional.webp",
        precio: 2500,
        pesoMin: "",
        pesoMax:"1kg",
        descripcion:"Sellador acrílico Premium, para aplicaciones en interiores y exteriores",
        caracteristicas: "Sikacryl® Profesional es un sellador acrílico versátil, de un componente, de buena tixotropía, adecuado para el sellado de juntas y fisuras interiores de bajo movimiento. Ideal para juntas verticales, horizontales e invertidas. Capacidad de movimiento ± 12,5%.",
        marca:"",
        categoria:"A",
        oferta: false,
    },
    {
        producto :"Sikalastic 560",
        id: 10,
        img : "../assets/img/Sikalastic-560.webp",
        precio: 31600,
        pesoMin: "",
        pesoMax:"20kg",
        descripcion:"Membrana líquida con poliuretano impermeabilizante para techos, basada en la Tecnología CO-Elástica (CET) de Sika",
        caracteristicas: "Sikalastic®-560 es una membrana líquida impermeabilizante con poliuretano, monocomponente, de aplicación en frío, altamente elástica y resistente a los rayos UV.",
        marca:"",
        categoria:"A",
        oferta: false,
    },
    {
        producto :"Mapei Mapelastic",
        id: 11,
        img : "../assets/img/mapelastic.webp",
        precio: 32000,
        pesoMin: "",
        pesoMax:"32kg",
        descripcion:"Mortero cementicio bicomponente elástico para la impermeabilización de hormigones, balcones, terrazas, baños y piscinas.",
        caracteristicas: "Presentación: conjuntos de 32 kg (parte A 24 kg parte B 8 kg).",
        marca:"",
        categoria:"A",
        oferta: false,
    },
    {
        producto :"Mapei Planiseal 288",
        id: 12,
        img : "../assets/img/planiseal-288.png",
        precio: 9000,
        pesoMin: "",
        pesoMax:"25kg",
        descripcion:"Mortero cementicio de dos componentes para la impermeabilización de estructuras subterráneas y de hormigón en general. ",
        caracteristicas: "Presentación: conjuntos de 25 kg (parte A 20 kg parte B 5 kg).",
        marca:"",
        categoria:"A",
        oferta: false,
    },
]